def fmmenu() :
    print("╔═════════════════╔═════════════════════╗═════════════════╗")
    print("║═════════════════╚═════FAMOUS BOOKS════╝═════════════════║")
    print("║         1-  Book1                                       ║ ")
    print("║         2-  Book2                                       ║ ")
    print("║         3-  Book3                                       ║ ")                            
    print("║         4-  Book4                                       ║ ")
    print("║         5-  Book5                                       ║ ")
    print("║         6-  Book6                                       ║ ")
    print("║                                                         ║ ")
    print("╚═════════════════════════════════════════════════════════╝ ")
    choice=input()
